/*!
 @file           bsp_flash.h
 @brief          bsp for flash
 @author         tqfx tqfx@foxmail.com
 @version        0
 @date           2021-06-11
 @copyright      Copyright (C) 2021 tqfx
 \n \n
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 \n \n
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 \n \n
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
*/

/* Define to prevent recursive inclusion */
#ifndef __BSP_FLASH_H__
#define __BSP_FLASH_H__

#include "bsp.h"

#include "main.h"

#include <stdint.h>

//#define FLASH_PAGE_TOTAL 0x20U
//#define FLASH_PAGE_TOTAL 0x80U
#define FLASH_PAGE_TOTAL 0x100U

#define FLASH_PAGE0  FLASH_BASE
#define FLASH_PAGE1  (FLASH_PAGE_SIZE + FLASH_PAGE0)
#define FLASH_PAGE2  (FLASH_PAGE_SIZE + FLASH_PAGE1)
#define FLASH_PAGE3  (FLASH_PAGE_SIZE + FLASH_PAGE2)
#define FLASH_PAGE4  (FLASH_PAGE_SIZE + FLASH_PAGE3)
#define FLASH_PAGE5  (FLASH_PAGE_SIZE + FLASH_PAGE4)
#define FLASH_PAGE6  (FLASH_PAGE_SIZE + FLASH_PAGE5)
#define FLASH_PAGE7  (FLASH_PAGE_SIZE + FLASH_PAGE6)
#define FLASH_PAGE8  (FLASH_PAGE_SIZE + FLASH_PAGE7)
#define FLASH_PAGE9  (FLASH_PAGE_SIZE + FLASH_PAGE8)
#define FLASH_PAGE10 (FLASH_PAGE_SIZE + FLASH_PAGE9)
#define FLASH_PAGE11 (FLASH_PAGE_SIZE + FLASH_PAGE10)
#define FLASH_PAGE12 (FLASH_PAGE_SIZE + FLASH_PAGE11)
#define FLASH_PAGE13 (FLASH_PAGE_SIZE + FLASH_PAGE12)
#define FLASH_PAGE14 (FLASH_PAGE_SIZE + FLASH_PAGE13)
#define FLASH_PAGE15 (FLASH_PAGE_SIZE + FLASH_PAGE14)
#define FLASH_PAGE16 (FLASH_PAGE_SIZE + FLASH_PAGE15)
#define FLASH_PAGE17 (FLASH_PAGE_SIZE + FLASH_PAGE16)
#define FLASH_PAGE18 (FLASH_PAGE_SIZE + FLASH_PAGE17)
#define FLASH_PAGE19 (FLASH_PAGE_SIZE + FLASH_PAGE18)
#define FLASH_PAGE20 (FLASH_PAGE_SIZE + FLASH_PAGE19)
#define FLASH_PAGE21 (FLASH_PAGE_SIZE + FLASH_PAGE20)
#define FLASH_PAGE22 (FLASH_PAGE_SIZE + FLASH_PAGE21)
#define FLASH_PAGE23 (FLASH_PAGE_SIZE + FLASH_PAGE22)
#define FLASH_PAGE24 (FLASH_PAGE_SIZE + FLASH_PAGE23)
#define FLASH_PAGE25 (FLASH_PAGE_SIZE + FLASH_PAGE24)
#define FLASH_PAGE26 (FLASH_PAGE_SIZE + FLASH_PAGE25)
#define FLASH_PAGE27 (FLASH_PAGE_SIZE + FLASH_PAGE26)
#define FLASH_PAGE28 (FLASH_PAGE_SIZE + FLASH_PAGE27)
#define FLASH_PAGE29 (FLASH_PAGE_SIZE + FLASH_PAGE28)
#define FLASH_PAGE30 (FLASH_PAGE_SIZE + FLASH_PAGE29)
#define FLASH_PAGE31 (FLASH_PAGE_SIZE + FLASH_PAGE30)

#if FLASH_PAGE_TOTAL <= 0x20U
#define FLASH_PAGE_END (FLASH_PAGE_SIZE + FLASH_PAGE31)
#else /* FLASH_PAGE_TOTAL > 0x20U */
#define FLASH_PAGE32  (FLASH_PAGE_SIZE + FLASH_PAGE31)
#define FLASH_PAGE33  (FLASH_PAGE_SIZE + FLASH_PAGE32)
#define FLASH_PAGE34  (FLASH_PAGE_SIZE + FLASH_PAGE33)
#define FLASH_PAGE35  (FLASH_PAGE_SIZE + FLASH_PAGE34)
#define FLASH_PAGE36  (FLASH_PAGE_SIZE + FLASH_PAGE35)
#define FLASH_PAGE37  (FLASH_PAGE_SIZE + FLASH_PAGE36)
#define FLASH_PAGE38  (FLASH_PAGE_SIZE + FLASH_PAGE37)
#define FLASH_PAGE39  (FLASH_PAGE_SIZE + FLASH_PAGE38)
#define FLASH_PAGE40  (FLASH_PAGE_SIZE + FLASH_PAGE39)
#define FLASH_PAGE41  (FLASH_PAGE_SIZE + FLASH_PAGE40)
#define FLASH_PAGE42  (FLASH_PAGE_SIZE + FLASH_PAGE41)
#define FLASH_PAGE43  (FLASH_PAGE_SIZE + FLASH_PAGE42)
#define FLASH_PAGE44  (FLASH_PAGE_SIZE + FLASH_PAGE43)
#define FLASH_PAGE45  (FLASH_PAGE_SIZE + FLASH_PAGE44)
#define FLASH_PAGE46  (FLASH_PAGE_SIZE + FLASH_PAGE45)
#define FLASH_PAGE47  (FLASH_PAGE_SIZE + FLASH_PAGE46)
#define FLASH_PAGE48  (FLASH_PAGE_SIZE + FLASH_PAGE47)
#define FLASH_PAGE49  (FLASH_PAGE_SIZE + FLASH_PAGE48)
#define FLASH_PAGE50  (FLASH_PAGE_SIZE + FLASH_PAGE49)
#define FLASH_PAGE51  (FLASH_PAGE_SIZE + FLASH_PAGE50)
#define FLASH_PAGE52  (FLASH_PAGE_SIZE + FLASH_PAGE51)
#define FLASH_PAGE53  (FLASH_PAGE_SIZE + FLASH_PAGE52)
#define FLASH_PAGE54  (FLASH_PAGE_SIZE + FLASH_PAGE53)
#define FLASH_PAGE55  (FLASH_PAGE_SIZE + FLASH_PAGE54)
#define FLASH_PAGE56  (FLASH_PAGE_SIZE + FLASH_PAGE55)
#define FLASH_PAGE57  (FLASH_PAGE_SIZE + FLASH_PAGE56)
#define FLASH_PAGE58  (FLASH_PAGE_SIZE + FLASH_PAGE57)
#define FLASH_PAGE59  (FLASH_PAGE_SIZE + FLASH_PAGE58)
#define FLASH_PAGE60  (FLASH_PAGE_SIZE + FLASH_PAGE59)
#define FLASH_PAGE61  (FLASH_PAGE_SIZE + FLASH_PAGE60)
#define FLASH_PAGE62  (FLASH_PAGE_SIZE + FLASH_PAGE61)
#define FLASH_PAGE63  (FLASH_PAGE_SIZE + FLASH_PAGE62)
#define FLASH_PAGE64  (FLASH_PAGE_SIZE + FLASH_PAGE63)
#define FLASH_PAGE65  (FLASH_PAGE_SIZE + FLASH_PAGE64)
#define FLASH_PAGE66  (FLASH_PAGE_SIZE + FLASH_PAGE65)
#define FLASH_PAGE67  (FLASH_PAGE_SIZE + FLASH_PAGE66)
#define FLASH_PAGE68  (FLASH_PAGE_SIZE + FLASH_PAGE67)
#define FLASH_PAGE69  (FLASH_PAGE_SIZE + FLASH_PAGE68)
#define FLASH_PAGE70  (FLASH_PAGE_SIZE + FLASH_PAGE69)
#define FLASH_PAGE71  (FLASH_PAGE_SIZE + FLASH_PAGE70)
#define FLASH_PAGE72  (FLASH_PAGE_SIZE + FLASH_PAGE71)
#define FLASH_PAGE73  (FLASH_PAGE_SIZE + FLASH_PAGE72)
#define FLASH_PAGE74  (FLASH_PAGE_SIZE + FLASH_PAGE73)
#define FLASH_PAGE75  (FLASH_PAGE_SIZE + FLASH_PAGE74)
#define FLASH_PAGE76  (FLASH_PAGE_SIZE + FLASH_PAGE75)
#define FLASH_PAGE77  (FLASH_PAGE_SIZE + FLASH_PAGE76)
#define FLASH_PAGE78  (FLASH_PAGE_SIZE + FLASH_PAGE77)
#define FLASH_PAGE79  (FLASH_PAGE_SIZE + FLASH_PAGE78)
#define FLASH_PAGE80  (FLASH_PAGE_SIZE + FLASH_PAGE79)
#define FLASH_PAGE81  (FLASH_PAGE_SIZE + FLASH_PAGE80)
#define FLASH_PAGE82  (FLASH_PAGE_SIZE + FLASH_PAGE81)
#define FLASH_PAGE83  (FLASH_PAGE_SIZE + FLASH_PAGE82)
#define FLASH_PAGE84  (FLASH_PAGE_SIZE + FLASH_PAGE83)
#define FLASH_PAGE85  (FLASH_PAGE_SIZE + FLASH_PAGE84)
#define FLASH_PAGE86  (FLASH_PAGE_SIZE + FLASH_PAGE85)
#define FLASH_PAGE87  (FLASH_PAGE_SIZE + FLASH_PAGE86)
#define FLASH_PAGE88  (FLASH_PAGE_SIZE + FLASH_PAGE87)
#define FLASH_PAGE89  (FLASH_PAGE_SIZE + FLASH_PAGE88)
#define FLASH_PAGE90  (FLASH_PAGE_SIZE + FLASH_PAGE89)
#define FLASH_PAGE91  (FLASH_PAGE_SIZE + FLASH_PAGE90)
#define FLASH_PAGE92  (FLASH_PAGE_SIZE + FLASH_PAGE91)
#define FLASH_PAGE93  (FLASH_PAGE_SIZE + FLASH_PAGE92)
#define FLASH_PAGE94  (FLASH_PAGE_SIZE + FLASH_PAGE93)
#define FLASH_PAGE95  (FLASH_PAGE_SIZE + FLASH_PAGE94)
#define FLASH_PAGE96  (FLASH_PAGE_SIZE + FLASH_PAGE95)
#define FLASH_PAGE97  (FLASH_PAGE_SIZE + FLASH_PAGE96)
#define FLASH_PAGE98  (FLASH_PAGE_SIZE + FLASH_PAGE97)
#define FLASH_PAGE99  (FLASH_PAGE_SIZE + FLASH_PAGE98)
#define FLASH_PAGE100 (FLASH_PAGE_SIZE + FLASH_PAGE99)
#define FLASH_PAGE101 (FLASH_PAGE_SIZE + FLASH_PAGE100)
#define FLASH_PAGE102 (FLASH_PAGE_SIZE + FLASH_PAGE101)
#define FLASH_PAGE103 (FLASH_PAGE_SIZE + FLASH_PAGE102)
#define FLASH_PAGE104 (FLASH_PAGE_SIZE + FLASH_PAGE103)
#define FLASH_PAGE105 (FLASH_PAGE_SIZE + FLASH_PAGE104)
#define FLASH_PAGE106 (FLASH_PAGE_SIZE + FLASH_PAGE105)
#define FLASH_PAGE107 (FLASH_PAGE_SIZE + FLASH_PAGE106)
#define FLASH_PAGE108 (FLASH_PAGE_SIZE + FLASH_PAGE107)
#define FLASH_PAGE109 (FLASH_PAGE_SIZE + FLASH_PAGE108)
#define FLASH_PAGE110 (FLASH_PAGE_SIZE + FLASH_PAGE109)
#define FLASH_PAGE111 (FLASH_PAGE_SIZE + FLASH_PAGE110)
#define FLASH_PAGE112 (FLASH_PAGE_SIZE + FLASH_PAGE111)
#define FLASH_PAGE113 (FLASH_PAGE_SIZE + FLASH_PAGE112)
#define FLASH_PAGE114 (FLASH_PAGE_SIZE + FLASH_PAGE113)
#define FLASH_PAGE115 (FLASH_PAGE_SIZE + FLASH_PAGE114)
#define FLASH_PAGE116 (FLASH_PAGE_SIZE + FLASH_PAGE115)
#define FLASH_PAGE117 (FLASH_PAGE_SIZE + FLASH_PAGE116)
#define FLASH_PAGE118 (FLASH_PAGE_SIZE + FLASH_PAGE117)
#define FLASH_PAGE119 (FLASH_PAGE_SIZE + FLASH_PAGE118)
#define FLASH_PAGE120 (FLASH_PAGE_SIZE + FLASH_PAGE119)
#define FLASH_PAGE121 (FLASH_PAGE_SIZE + FLASH_PAGE120)
#define FLASH_PAGE122 (FLASH_PAGE_SIZE + FLASH_PAGE121)
#define FLASH_PAGE123 (FLASH_PAGE_SIZE + FLASH_PAGE122)
#define FLASH_PAGE124 (FLASH_PAGE_SIZE + FLASH_PAGE123)
#define FLASH_PAGE125 (FLASH_PAGE_SIZE + FLASH_PAGE124)
#define FLASH_PAGE126 (FLASH_PAGE_SIZE + FLASH_PAGE125)
#define FLASH_PAGE127 (FLASH_PAGE_SIZE + FLASH_PAGE126)
#endif /* FLASH_PAGE_TOTAL <= 0x20U */

#if FLASH_PAGE_TOTAL <= 0x80U
#define FLASH_PAGE_END (FLASH_PAGE_SIZE + FLASH_PAGE127)
#else /* FLASH_PAGE_TOTAL > 0x80U */
#define FLASH_PAGE128 (FLASH_PAGE_SIZE + FLASH_PAGE127)
#define FLASH_PAGE129 (FLASH_PAGE_SIZE + FLASH_PAGE128)
#define FLASH_PAGE130 (FLASH_PAGE_SIZE + FLASH_PAGE129)
#define FLASH_PAGE131 (FLASH_PAGE_SIZE + FLASH_PAGE130)
#define FLASH_PAGE132 (FLASH_PAGE_SIZE + FLASH_PAGE131)
#define FLASH_PAGE133 (FLASH_PAGE_SIZE + FLASH_PAGE132)
#define FLASH_PAGE134 (FLASH_PAGE_SIZE + FLASH_PAGE133)
#define FLASH_PAGE135 (FLASH_PAGE_SIZE + FLASH_PAGE134)
#define FLASH_PAGE136 (FLASH_PAGE_SIZE + FLASH_PAGE135)
#define FLASH_PAGE137 (FLASH_PAGE_SIZE + FLASH_PAGE136)
#define FLASH_PAGE138 (FLASH_PAGE_SIZE + FLASH_PAGE137)
#define FLASH_PAGE139 (FLASH_PAGE_SIZE + FLASH_PAGE138)
#define FLASH_PAGE140 (FLASH_PAGE_SIZE + FLASH_PAGE139)
#define FLASH_PAGE141 (FLASH_PAGE_SIZE + FLASH_PAGE140)
#define FLASH_PAGE142 (FLASH_PAGE_SIZE + FLASH_PAGE141)
#define FLASH_PAGE143 (FLASH_PAGE_SIZE + FLASH_PAGE142)
#define FLASH_PAGE144 (FLASH_PAGE_SIZE + FLASH_PAGE143)
#define FLASH_PAGE145 (FLASH_PAGE_SIZE + FLASH_PAGE144)
#define FLASH_PAGE146 (FLASH_PAGE_SIZE + FLASH_PAGE145)
#define FLASH_PAGE147 (FLASH_PAGE_SIZE + FLASH_PAGE146)
#define FLASH_PAGE148 (FLASH_PAGE_SIZE + FLASH_PAGE147)
#define FLASH_PAGE149 (FLASH_PAGE_SIZE + FLASH_PAGE148)
#define FLASH_PAGE150 (FLASH_PAGE_SIZE + FLASH_PAGE149)
#define FLASH_PAGE151 (FLASH_PAGE_SIZE + FLASH_PAGE150)
#define FLASH_PAGE152 (FLASH_PAGE_SIZE + FLASH_PAGE151)
#define FLASH_PAGE153 (FLASH_PAGE_SIZE + FLASH_PAGE152)
#define FLASH_PAGE154 (FLASH_PAGE_SIZE + FLASH_PAGE153)
#define FLASH_PAGE155 (FLASH_PAGE_SIZE + FLASH_PAGE154)
#define FLASH_PAGE156 (FLASH_PAGE_SIZE + FLASH_PAGE155)
#define FLASH_PAGE157 (FLASH_PAGE_SIZE + FLASH_PAGE156)
#define FLASH_PAGE158 (FLASH_PAGE_SIZE + FLASH_PAGE157)
#define FLASH_PAGE159 (FLASH_PAGE_SIZE + FLASH_PAGE158)
#define FLASH_PAGE160 (FLASH_PAGE_SIZE + FLASH_PAGE159)
#define FLASH_PAGE161 (FLASH_PAGE_SIZE + FLASH_PAGE160)
#define FLASH_PAGE162 (FLASH_PAGE_SIZE + FLASH_PAGE161)
#define FLASH_PAGE163 (FLASH_PAGE_SIZE + FLASH_PAGE162)
#define FLASH_PAGE164 (FLASH_PAGE_SIZE + FLASH_PAGE163)
#define FLASH_PAGE165 (FLASH_PAGE_SIZE + FLASH_PAGE164)
#define FLASH_PAGE166 (FLASH_PAGE_SIZE + FLASH_PAGE165)
#define FLASH_PAGE167 (FLASH_PAGE_SIZE + FLASH_PAGE166)
#define FLASH_PAGE168 (FLASH_PAGE_SIZE + FLASH_PAGE167)
#define FLASH_PAGE169 (FLASH_PAGE_SIZE + FLASH_PAGE168)
#define FLASH_PAGE170 (FLASH_PAGE_SIZE + FLASH_PAGE169)
#define FLASH_PAGE171 (FLASH_PAGE_SIZE + FLASH_PAGE170)
#define FLASH_PAGE172 (FLASH_PAGE_SIZE + FLASH_PAGE171)
#define FLASH_PAGE173 (FLASH_PAGE_SIZE + FLASH_PAGE172)
#define FLASH_PAGE174 (FLASH_PAGE_SIZE + FLASH_PAGE173)
#define FLASH_PAGE175 (FLASH_PAGE_SIZE + FLASH_PAGE174)
#define FLASH_PAGE176 (FLASH_PAGE_SIZE + FLASH_PAGE175)
#define FLASH_PAGE177 (FLASH_PAGE_SIZE + FLASH_PAGE176)
#define FLASH_PAGE178 (FLASH_PAGE_SIZE + FLASH_PAGE177)
#define FLASH_PAGE179 (FLASH_PAGE_SIZE + FLASH_PAGE178)
#define FLASH_PAGE180 (FLASH_PAGE_SIZE + FLASH_PAGE179)
#define FLASH_PAGE181 (FLASH_PAGE_SIZE + FLASH_PAGE180)
#define FLASH_PAGE182 (FLASH_PAGE_SIZE + FLASH_PAGE181)
#define FLASH_PAGE183 (FLASH_PAGE_SIZE + FLASH_PAGE182)
#define FLASH_PAGE184 (FLASH_PAGE_SIZE + FLASH_PAGE183)
#define FLASH_PAGE185 (FLASH_PAGE_SIZE + FLASH_PAGE184)
#define FLASH_PAGE186 (FLASH_PAGE_SIZE + FLASH_PAGE185)
#define FLASH_PAGE187 (FLASH_PAGE_SIZE + FLASH_PAGE186)
#define FLASH_PAGE188 (FLASH_PAGE_SIZE + FLASH_PAGE187)
#define FLASH_PAGE189 (FLASH_PAGE_SIZE + FLASH_PAGE188)
#define FLASH_PAGE190 (FLASH_PAGE_SIZE + FLASH_PAGE189)
#define FLASH_PAGE191 (FLASH_PAGE_SIZE + FLASH_PAGE190)
#define FLASH_PAGE192 (FLASH_PAGE_SIZE + FLASH_PAGE191)
#define FLASH_PAGE193 (FLASH_PAGE_SIZE + FLASH_PAGE192)
#define FLASH_PAGE194 (FLASH_PAGE_SIZE + FLASH_PAGE193)
#define FLASH_PAGE195 (FLASH_PAGE_SIZE + FLASH_PAGE194)
#define FLASH_PAGE196 (FLASH_PAGE_SIZE + FLASH_PAGE195)
#define FLASH_PAGE197 (FLASH_PAGE_SIZE + FLASH_PAGE196)
#define FLASH_PAGE198 (FLASH_PAGE_SIZE + FLASH_PAGE197)
#define FLASH_PAGE199 (FLASH_PAGE_SIZE + FLASH_PAGE198)
#define FLASH_PAGE200 (FLASH_PAGE_SIZE + FLASH_PAGE199)
#define FLASH_PAGE201 (FLASH_PAGE_SIZE + FLASH_PAGE200)
#define FLASH_PAGE202 (FLASH_PAGE_SIZE + FLASH_PAGE201)
#define FLASH_PAGE203 (FLASH_PAGE_SIZE + FLASH_PAGE202)
#define FLASH_PAGE204 (FLASH_PAGE_SIZE + FLASH_PAGE203)
#define FLASH_PAGE205 (FLASH_PAGE_SIZE + FLASH_PAGE204)
#define FLASH_PAGE206 (FLASH_PAGE_SIZE + FLASH_PAGE205)
#define FLASH_PAGE207 (FLASH_PAGE_SIZE + FLASH_PAGE206)
#define FLASH_PAGE208 (FLASH_PAGE_SIZE + FLASH_PAGE207)
#define FLASH_PAGE209 (FLASH_PAGE_SIZE + FLASH_PAGE208)
#define FLASH_PAGE210 (FLASH_PAGE_SIZE + FLASH_PAGE209)
#define FLASH_PAGE211 (FLASH_PAGE_SIZE + FLASH_PAGE210)
#define FLASH_PAGE212 (FLASH_PAGE_SIZE + FLASH_PAGE211)
#define FLASH_PAGE213 (FLASH_PAGE_SIZE + FLASH_PAGE212)
#define FLASH_PAGE214 (FLASH_PAGE_SIZE + FLASH_PAGE213)
#define FLASH_PAGE215 (FLASH_PAGE_SIZE + FLASH_PAGE214)
#define FLASH_PAGE216 (FLASH_PAGE_SIZE + FLASH_PAGE215)
#define FLASH_PAGE217 (FLASH_PAGE_SIZE + FLASH_PAGE216)
#define FLASH_PAGE218 (FLASH_PAGE_SIZE + FLASH_PAGE217)
#define FLASH_PAGE219 (FLASH_PAGE_SIZE + FLASH_PAGE218)
#define FLASH_PAGE220 (FLASH_PAGE_SIZE + FLASH_PAGE219)
#define FLASH_PAGE221 (FLASH_PAGE_SIZE + FLASH_PAGE220)
#define FLASH_PAGE222 (FLASH_PAGE_SIZE + FLASH_PAGE221)
#define FLASH_PAGE223 (FLASH_PAGE_SIZE + FLASH_PAGE222)
#define FLASH_PAGE224 (FLASH_PAGE_SIZE + FLASH_PAGE223)
#define FLASH_PAGE225 (FLASH_PAGE_SIZE + FLASH_PAGE224)
#define FLASH_PAGE226 (FLASH_PAGE_SIZE + FLASH_PAGE225)
#define FLASH_PAGE227 (FLASH_PAGE_SIZE + FLASH_PAGE226)
#define FLASH_PAGE228 (FLASH_PAGE_SIZE + FLASH_PAGE227)
#define FLASH_PAGE229 (FLASH_PAGE_SIZE + FLASH_PAGE228)
#define FLASH_PAGE230 (FLASH_PAGE_SIZE + FLASH_PAGE229)
#define FLASH_PAGE231 (FLASH_PAGE_SIZE + FLASH_PAGE230)
#define FLASH_PAGE232 (FLASH_PAGE_SIZE + FLASH_PAGE231)
#define FLASH_PAGE233 (FLASH_PAGE_SIZE + FLASH_PAGE232)
#define FLASH_PAGE234 (FLASH_PAGE_SIZE + FLASH_PAGE233)
#define FLASH_PAGE235 (FLASH_PAGE_SIZE + FLASH_PAGE234)
#define FLASH_PAGE236 (FLASH_PAGE_SIZE + FLASH_PAGE235)
#define FLASH_PAGE237 (FLASH_PAGE_SIZE + FLASH_PAGE236)
#define FLASH_PAGE238 (FLASH_PAGE_SIZE + FLASH_PAGE237)
#define FLASH_PAGE239 (FLASH_PAGE_SIZE + FLASH_PAGE238)
#define FLASH_PAGE240 (FLASH_PAGE_SIZE + FLASH_PAGE239)
#define FLASH_PAGE241 (FLASH_PAGE_SIZE + FLASH_PAGE240)
#define FLASH_PAGE242 (FLASH_PAGE_SIZE + FLASH_PAGE241)
#define FLASH_PAGE243 (FLASH_PAGE_SIZE + FLASH_PAGE242)
#define FLASH_PAGE244 (FLASH_PAGE_SIZE + FLASH_PAGE243)
#define FLASH_PAGE245 (FLASH_PAGE_SIZE + FLASH_PAGE244)
#define FLASH_PAGE246 (FLASH_PAGE_SIZE + FLASH_PAGE245)
#define FLASH_PAGE247 (FLASH_PAGE_SIZE + FLASH_PAGE246)
#define FLASH_PAGE248 (FLASH_PAGE_SIZE + FLASH_PAGE247)
#define FLASH_PAGE249 (FLASH_PAGE_SIZE + FLASH_PAGE248)
#define FLASH_PAGE250 (FLASH_PAGE_SIZE + FLASH_PAGE249)
#define FLASH_PAGE251 (FLASH_PAGE_SIZE + FLASH_PAGE250)
#define FLASH_PAGE252 (FLASH_PAGE_SIZE + FLASH_PAGE251)
#define FLASH_PAGE253 (FLASH_PAGE_SIZE + FLASH_PAGE252)
#define FLASH_PAGE254 (FLASH_PAGE_SIZE + FLASH_PAGE253)
#define FLASH_PAGE255 (FLASH_PAGE_SIZE + FLASH_PAGE254)
#endif /* FLASH_PAGE_TOTAL <= 0x80U */

#if FLASH_PAGE_TOTAL <= 0x100U
#define FLASH_PAGE_END (FLASH_PAGE_SIZE + FLASH_PAGE255)
#endif /* FLASH_PAGE_TOTAL <= 0x100U */

__BEGIN_DECLS

extern uint32_t flash_page(uint32_t addr);

extern uint32_t flash_page_next(uint32_t addr);

extern int8_t flash_erase(uint32_t addr,
                          uint32_t num);
/*!
 @brief          read data for flash
 @param[in]      addr: flash address
 @param[out]     buf: data point
 @param[in]      len: data num
*/
extern void flash_read(uint32_t addr,
                       void *buf,
                       uint32_t len);

/*!
 @brief          write data to one page of flash
 @param[in]      addr: flash address
 @param[in]      buf: data point
 @param[in]      len: data num
 @return         The execution state of the function
  @retval        0  success
  @retval        -1 failure
*/
extern int8_t flash_write(uint32_t addr,
                          void *buf,
                          uint32_t len);

/*!
 @brief          write data to some pages of flash
 @param[in]      addr: flash start address
 @param[in]      addr_end: flash end address
 @param[in]      buf: data point
 @param[in]      len: data num
 @return         The execution state of the function
  @retval        0  success
  @retval        -1 failure
*/
extern int8_t flash_writen(uint32_t start,
                           uint32_t end,
                           void *buf,
                           uint32_t len);

__END_DECLS

/* Enddef to prevent recursive inclusion */
#endif /* __BSP_FLASH_H__ */

/* END OF FILE */
