# core
macro(append_option value)
  foreach(option ${ARGN})
    if(${value})
      string(FIND "${${value}}" ${option} result)
      if(${result} EQUAL -1)
        set(${value} "${${value}} ${option}")
      endif()
    else()
      set(${value} ${option})
    endif()
  endforeach()
endmacro()
# FLAGS
macro(append_flag)
  foreach(flag ${ARGN})
    append_option(CMAKE_C_FLAGS ${flag})
    append_option(CMAKE_CXX_FLAGS ${flag})
  endforeach()
endmacro()
# CFLAGS
macro(append_cflag)
  foreach(flag ${ARGN})
    append_option(CMAKE_C_FLAGS ${flag})
  endforeach()
endmacro()
# CXXFLAGS
macro(append_cxxflag)
  foreach(flag ${ARGN})
    append_option(CMAKE_CXX_FLAGS ${flag})
  endforeach()
endmacro()
